version: "3.3"
services:
  db-com:
    image: postgres:14
    container_name: db-com
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe123qwe
      POSTGRES_DB: db_development

  server-com:
    build: .
    container_name: server-com
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3003 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "3003:3003"
    depends_on:
      - db-com

  worker:
    build: .
    command: bash -c 'rake sneakers:run'
    container_name: worker
    volumes:
      - .:/app
    environment:
      WORKERS: Compiler
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db-com

networks:
  default:
    external:
      name: charlist_project_general